name: View Transitions API
id: frontend/animation/view-transitions (@vince)
category: frontend/animation
description: >
  Native View Transitions API patterns - same-document SPA transitions,
  cross-document MPA transitions, shared element hero animations,
  pseudo-element styling, feature detection, and accessibility.
version: 1.0.0
author: vince
cli_description: Page transition animations
usage_guidance: Use when implementing page transitions with View Transitions API.

keywords:
  - View Transitions API
  - startViewTransition
  - view-transition-name
  - view-transition-class
  - "@view-transition"
  - "::view-transition"
  - "::view-transition-old"
  - "::view-transition-new"
  - "::view-transition-group"
  - "::view-transition-image-pair"
  - pageswap
  - pagereveal
  - ViewTransition
  - active-view-transition-type
  - shared element transition
  - hero animation
  - page transitions
  - MPA transitions
  - cross-document navigation
  - match-element

triggers:
  - view transition
  - page transition
  - state transition animation
  - cross document transition
  - shared element
  - hero image animation
  - startViewTransition
  - view-transition-name
  - MPA animation
  - native page animation

files:
  - SKILL.md
  - reference.md
  - examples/core.md
  - examples/spa.md
  - examples/shared-elements.md

related_skills:
  - frontend/animation/framer-motion (@vince)
  - frontend/accessibility (@vince)

prerequisites: []

tech_stack:
  - View Transitions API (browser native)
  - CSS animations
  - Web Animations API
  - JavaScript/TypeScript

browser_support:
  chrome: "111+"
  safari: "18+"
  firefox: "144+"
  edge: "111+"
  cross_document:
    chrome: "126+"
    safari: partial
    firefox: planned
    edge: "126+"
