id: mobile/expo (@vince)
name: Expo Development
description: Build production-ready React Native apps with Expo managed workflow, Expo Router for file-based navigation, and EAS for cloud builds and OTA updates
category: mobile
author: vince

keywords:
  - expo
  - expo-router
  - eas build
  - eas update
  - expo-dev-client
  - expo prebuild
  - continuous native generation
  - cng
  - managed workflow
  - ota updates
  - config plugins
  - expo-notifications
  - expo-camera
  - expo-location
  - development builds
  - app.config.ts
  - eas.json
  - expo-video
  - expo-audio
  - expo-router/ui
  - headless tabs
  - TabList
  - TabTrigger
  - TabSlot
  - native tabs
  - NativeTabs
  - expo-router/unstable-native-tabs
  - edge-to-edge
  - expo/fetch
  - expo-file-system
  - expo-glass-effect
  - expo-app-integrity
  - dismissTo
  - dismissAll
  - prefetch

triggers:
  - expo
  - expo-router
  - EAS Build
  - EAS Update
  - expo-dev-client
  - app.config.js
  - app.config.ts
  - app.json expo
  - expo prebuild
  - npx expo
  - eas.json
  - expo-constants
  - expo-notifications
  - Continuous Native Generation
  - CNG
  - EXPO_PUBLIC_
  - runtimeVersion
  - expo-camera
  - expo-location
  - expo-image
  - expo-font
  - expo-video
  - expo-audio
  - expo-router/ui
  - TabList
  - TabTrigger
  - TabSlot
  - headless tabs
  - native tabs
  - edge-to-edge Android
  - expo/fetch
  - expo-router/unstable-native-tabs
  - NativeTabs
  - expo-file-system
  - dismissTo
  - dismissAll

version: 1.0.0
